[package]
name = "ts"
description = "Prepend a timestamp to everything from stdin"
license = "MIT"
version = "2.0.0"
authors = ["Brian Caswell <bmc@shmoo.com>"]
edition = "2021"

[dependencies]
chrono = {version= "0.4", features = ["std"]}

[profile.release]
opt-level="z"
lto=true